#= require bone_tree

window.tree = new BoneTree.Views.Tree

fileTreeData = JSON.parse($('#code_content').val())

fileTreeData.each (file) ->
  tree.add file.path, file

# Use special docs link
tree.remove "docs"
tree.add "Documentation.documentation",
  type: "documentation"
  path: "docs"

tree.bind 'openFile', (e, file) ->
  if e?.which is 3
    menu = new Boner.Views.Menu
      items:
        rename: ->
          renameFile(file, file.get('path'))
        delete: ->
          deleteFile(file)
      event: e

    $('body').append(menu.render().el)
  else
    openFile(file)

$('.sidebar').append(tree.render().$el)

# hack to hide _ files generated by entities
tree.$el.find('.directory').on 'click', ->
  $(this).find('.file').filter((index, el) ->
    $(el).text()[0] is '_'
  ).hide()

# ideally we should only prevent the
# context menu on the particular element
$(document).on 'contextmenu', (e) ->
  false
